### ISSUE TITLE
Re-implement issue

### ISSUE THREAD

**Issue by DannyChiu** [yan-gao-GY/Flower-SpeechBrain#1]
Hi, thanks for the awesome work.
However, when I tried to re-implement this repo, there were some problems.
Since I don't have the pre-train model, I tried to train the model.

After downloading Common voice 6.1 Franch dataset, I followed the example code in the README.md

Here is the code I used.
First start the server.
``` python
python server.py --data_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr --tr_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr/train.tsv --test_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr/test.tsv --weight_strategy num
```

Then launch a client on the other terminal
``` python
python client.py --cid 0  --data_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr --tr_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr/ --dev_path ./dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr/dev.tsv
```
**The problem is that after I start to run the code.
The server was beginning to do the evaluation on the client 19999, instead of train the model.**

Could you please tell me how to solve this problem?
Thank you so much.

**Comment by yan-gao-GY** [comment]
Hi, the client 19999 is just a fake client on the server side which is created only for the evaluation process on test set. Sorry it's a bit confusing, but it actually could be any name. After the initial evaluation, the training will start.

**Comment by DannyChiu** [comment]
Hi, Thank you for your kindly reply.
It seems it worked when I tried to train the model with only **one client**  by setting the server.py parameter to `--min_fit_clients 1` and `--min_available_clients 1`.

However, I am wondering that is there pre-train model that we can download to get a better result in this repo?
Or how can we train a pre-train model?

Also, what is the `client 9999` used for?

Again, thank you so much for replying.

**Comment by mnabihali** [comment]
Dear I encounter this problem,

 `FileNotFoundError:    /home/mnabih/Flower-SpeechBrain/dataset_fr/fr/cv-corpus-6.1-2020-12-11/fr/train_0.tsv doesn't exist, verify your dataset!`

Do you know why and how can I solve it.
